os: linux
sudo: required
language: python
services: docker
before_install:
  - docker pull sgorava/arch-blender
  - git clone --depth 1 https://github.com/GlPortal/glportal-data.git
before_script:
  - docker run -it sgorava/arch-blender blender --version
script:
  - docker run -it -v $(pwd)/tests:/data -v $(pwd)/addon:/usr/share/blender/2.79/scripts/addons/toGlPortalXml -v $(pwd)/glportal-data:/root/.glportal/data sgorava/arch-blender
